server:
  port: 10102
spring:
  application:
    name: eureka-client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://replica1:10002/eureka/,http://replica2:10003/eureka/ #同时注册到两个注册中心