server:
  port: 10103
spring:
  application:
    name: eureka-client
eureka:
  client:
    register-with-eureka: true #是否将自己注册到eureka服务端上去
    fetch-registry: true #是否获取eureka服务端上注册的服务列表
    service-url:
      defaultZone: http://xp:123456@localhost:10004/eureka/  # 指定注册中心地址
    enabled: true  # 启用eureka客户端
    registry-fetch-interval-seconds: 30  #定义去eureka服务端获取服务列表的时间间隔
  instance:  #eureka客户端实例配置
    lease-renewal-interval-in-seconds: 30  #定义服务多久去注册中心续约
    lease-expiration-duration-in-seconds: 90  #定义服务多久不去续约认为服务失效
    metadata-map:
      zone: china #所在区域
    hostname: localhost  #服务主机名称
    prefer-ip-address: false  #是否优先使用ip来作为主机名