server:
  port: 10105
spring:
  application:
    name: user-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://xp:123456@localhost:10004/eureka/